llm:
  llm_enrichment: gpt-5.4-nano
  llm_query: gpt-5.4-nano
  llm_answer: gpt-5.4-mini

embedding:
  embedding_model: text-embedding-3-small


# vector_store: 1: chroma; 2: pinecone  
vector_DB:
  vector_store: 1 
  legal_index: German_Law
  namespace_Mietrecht: Mietrecht
  namespace_Steuerrecht: Steuerrecht

# mode: 1 , classic(dense+spare-bm25)+reranker), 2: BlendedFlashRankRetriever
# weight_hybrid=0.5, weight_reranker= 1 - weight_hybrid=0.5
retriever:
  retriever_mode: 2
  weight_hybrid: 0.4
  top_k: 8
  top_bm25_k: 30


chunking:
  size: 1000
  overlap: 200
  batch_size: 20



# Neue Sektion für Netzwerk / Client Settings
# ignore_ssl: False (as default, using True for test)
network:
  px_host: "127.0.0.1"
  px_port: 3128
  timeout: 60.0
  retries: 3
  ignore_ssl: False

paths:
  documents: data/dokumente_mietrecht
  rag_vector_db: chroma_legal_rag